# 本地 Nginx 部署，访问地址：https://hxkj.vip

#本次流程包含几个步骤，有多少个就写多少个，这边简单部署的话，用一个就够了
stages:
  - deploy

# 任务名称
deploy_job:
  # 当前执行哪个步骤
  stage: deploy
  only:
    # 指定当且仅当master分支有变动时，触发构建任务
    - master
  script:
    # 安装依赖
    - yarn
    # 运行项目打包命令
    - yarn build
    # 进入打包输出目录
    - cd ./dist
    # 压缩所有文件
    - tar -zcvf hxkj.tar.gz *
    # 将压缩文件移动到 nginx 站点根目录
    - mv hxkj.tar.gz /usr/share/nginx/html/
    # 进入 nginx 站点根目录
    - cd /usr/share/nginx/html
    # 解压并覆盖原有文件
    - tar -zxvf hxkj.tar.gz
    # 移除压缩包
    - rm -f hxkj.tar.gz
